face:
  work: 0
  store: 1
  friends: 2
  battery: 3
  home: 4
  driving: 5
  gym: 6
  restaurant: 7
  lost: 8
  dunno: 9
hands:
  elle:
    servo: 0
    range: 2160
    min: 700
    max: 2150
  jenne:
    servo: 1
    range: 2160
    min: 700
    max: 2177
  becky:
    servo: 2
    range: 2160
    min: 700
    max: 2190
  htb:
    servo: 3
    range: 2160
    min: 700
    max: 2135
