face:
  work: 0
  lost: 1
  gym: 2
  other: 3
  driving: 4
  home: 5
  battery: 6
  friends: 7
  restaurant: 8
  store: 9
hands:
  elle:
    servo: 0
    range: 2160
    min: 650
    max: 2145
  jenne:
    servo: 1
    range: 2160
    min: 700
    max: 2120
  becky:
    servo: 2
    range: 2160
    min: 700
    max: 2190
  htb:
    servo: 3
    range: 2160
    min: 710
    max: 2145
